V3 Docs workflow
Synthetixio/synthetix-v3 pull request #1051
Opened 2022-08-22 20:43 UTC by noahlitvin

2022-08-22 22:15 UTC, dbeal-eth requested changes
would be greati f you could add a CI step to generate the docs as well and export an artifact or site or something

2022-08-22 22:15 UTC, dbeal-eth commented on packages/core-contracts/contracts/interfaces/IERC721Enumerable.sol
>      function totalSupply() external view returns (uint256);
returns the number of individual tokens in existance for this contract

2022-08-22 22:15 UTC, dbeal-eth commented on packages/core-modules/contracts/modules/NftModule.sol
> +contract NftModule is INftModule, ERC721Enumerable, NftStorage, InitializableMixin, OwnableMixin {
ooh this is beyond a doc change, its a code change. is this intentional? I can agree it the change in general.

2022-08-22 22:15 UTC, dbeal-eth commented on packages/synthetix-main/contracts/interfaces/IAccountTokenModule.sol
> +    /// @notice mints a new token (NFT) with the "requestedAccountId" id owned by "owner". It can ol=nly be called by the system
typo

2022-08-22 22:15 UTC, dbeal-eth commented on packages/synthetix-main/contracts/interfaces/IAccountTokenModule.sol
> +     * @dev Safely transfers `tokenId` token from `from` to `to`.
transfers `tokenId` token from `from` to `to` with additional checks.

2022-08-23 14:58 UTC, ajsantander approved these changes
LGTM

2022-08-23 16:47 UTC, merged