feat: add slippage to atomic order buy and sell
Synthetixio/synthetix-v3 pull request #1400
Opened 2023-01-31 17:46 UTC by Rickk137

2023-01-31 18:19 UTC, sunnyvempati reviewed
can you add a specific test for this `minimumReceived` and check nothing gets deposited to market manager, nothing is collected by fee collector, everything is reverted properly?

2023-02-03 02:17 UTC, sunnyvempati approved these changes
🚢 it

2023-02-03 02:17 UTC, sunnyvempati commented on markets/spot-market/test/AtomicOrderModule.buy.test.ts
> +    });
checking revert is prolly enough but good sanity checks 😄

2023-02-03 13:38 UTC, noahlitvin requested changes

2023-02-03 13:38 UTC, noahlitvin commented on markets/spot-market/contracts/interfaces/IAtomicOrderModule.sol
>       * @return synthReturned Synth received on the trade based on amount provided by trader.
Add natspect for `minAmountReceived` plz

2023-02-03 13:38 UTC, noahlitvin commented on markets/spot-market/contracts/interfaces/IAtomicOrderModule.sol
>       * @return amountReturned Amount of snxUSD returned to user based on synth provided by trader.
Add natspect for `minAmountReceived` plz

2023-02-03 13:38 UTC, noahlitvin commented on markets/spot-market/contracts/modules/AtomicOrderModule.sol
> +            revert InsufficientReturnAmount(minAmountReceived, synthAmount);
Rename to `InsufficientAmountReceived` ?

2023-02-03 13:38 UTC, noahlitvin commented on markets/spot-market/contracts/modules/AtomicOrderModule.sol
> +            revert InsufficientReturnAmount(minAmountReceived, returnAmount);
Rename to InsufficientAmountReceived ?

2023-02-03 13:38 UTC, noahlitvin commented on markets/spot-market/contracts/modules/AtomicOrderModule.sol
> +            revert InsufficientReturnAmount(minAmountReceived, returnAmount);
Also, maybe we move this up under the process fee call? Would save a little gas I think?

2023-02-03 15:54 UTC, noahlitvin approved these changes

2023-02-03 15:54 UTC, merged