Feature/more market views
Synthetixio/synthetix-v3 pull request #1646
Opened 2023-06-07 09:38 UTC by davidvuong

Still WIP

2023-06-07 21:47 UTC, sunnyvempati requested changes
we should chat so i can understand the severity of the problem for keepers.  

adding storage is a pretty expensive solution (esp uint set).  wondering if subgraphs are enough to solve this, even though they're not as reliant.  otherwise, we'll have to figure out a more cost effective solution (maybe a linked list for cheaper insertion/deletion?)

2023-06-07 21:47 UTC, sunnyvempati commented on markets/perps-market/contracts/storage/PerpsMarket.sol
> +        SetUtil.UintSet asyncOrdersSet;
using a `UintSet` is very expensive as it creates an array and a mapping.  Generally speaking, we shouldn't be adding additional storage variables to contracts if its not serving the contract itself.  View functions are ok, but adding storage is not a negligible cost unfortunately.

2023-06-07 21:47 UTC, sunnyvempati commented on markets/perps-market/contracts/interfaces/IPerpsMarketModule.sol
> +    }
nicee

2023-06-08 04:44 UTC, davidvuong commented
> we should chat so i can understand the severity of the problem for keepers.

Yeah sure. A keeper on startup and throughout its lifetime needs know what orders are pending for execution. So on initial startup, a keeper can:

1. Spam `eth_getLogs` from block `n` until they reach `latestBlock`
2. Do (1) but cached and track the last block number to avoid reindexing on restart
3. Use an OTS indexing solution like The Graph
4. Pagination on the contract

Contract pagination is by far the fastest, easiest to use, and cheapest from the perspective of a keeper. Knowing the size, you can page out calls in a single `eth_call` to a multicall contract. With a large enough page size, you can probably fit everything you need in a single call.

We have something like this in PerpsV2 and it's quite useful. 

> we'll have to figure out a more cost effective solution (maybe a linked list for cheaper insertion/deletion?)

I'm easy. This PR is still in draft and WIP. There are more changes to be introduced. That said, just looking at `UintSet`, both `.add` and `.remove` operations are constant time? `.add` is just a `.push` and `.remove` is an index lookup, swap with tail and then `.pop`. I haven't looked at gas cost yet though.

2023-06-08 17:40 UTC, sunnyvempati commented
@davidvuong 

> Contract pagination is by far the fastest, easiest to use, and cheapest from the perspective of a keeper. Knowing the size, you can page out calls in a single eth_call to a multicall contract. With a large enough page size, you can probably fit everything you need in a single call.

Cheap for keepers, but not for traders committing orders.  My hope is we have much better eventing than v2x and let the graph / other solutions being discussed fill in the gaps for keepers.  

Also, I think we can layer this solution for keepers in later once we get the core functionality completed.  This isn't really necessary for getting perps v3 into audit.  Hopefully it will give us an easier way to assess the gas costs once we're code complete and can have baseline gas fee results.

2023-06-09 01:43 UTC, leomassazza commented
After some thinking, I agree we should (if possible) improve on-chain for users (traders) and off-chain for keepers/monitoring.

2023-06-09 05:06 UTC, davidvuong commented
Pagination has been removed as per discussion above.

2023-06-09 16:42 UTC, sunnyvempati approved these changes
🚢 it

2023-06-09 16:42 UTC, sunnyvempati commented on markets/perps-market/contracts/storage/PerpsMarket.sol
> +import {AccessError} from "@synthetixio/core-contracts/contracts/errors/AccessError.sol";
can omit

2023-06-09 16:44 UTC, sunnyvempati commented on markets/perps-market/contracts/modules/AsyncOrderModule.sol
> +    using SetUtil for SetUtil.UintSet;
.

2023-06-09 16:44 UTC, sunnyvempati commented on markets/perps-market/contracts/modules/AsyncOrderModule.sol
> +import {SetUtil} from "@synthetixio/core-contracts/contracts/utils/SetUtil.sol";
.

2023-06-10 18:15 UTC, merged