SIP-326, additional pool configuration
Synthetixio/synthetix-v3 pull request #1719
Opened 2023-07-12 21:20 UTC by Rickk137

2023-07-13 12:19 UTC, noahlitvin commented on protocol/synthetix/contracts/modules/core/PoolModule.sol
> +    function setPoolCollateralIssuanceRatioD18(
Unsure if we need D18 in the function name here? (Don't think we're doing this elsewhere.) Good to have it clarify in the parameter name though.

2023-07-13 12:20 UTC, noahlitvin commented on protocol/synthetix/contracts/modules/core/PoolModule.sol
> +    function getPoolCollateralIssuanceRatioD18(
Same as above

2023-07-13 12:21 UTC, noahlitvin commented on protocol/synthetix/contracts/modules/core/IssueUSDModule.sol
> +            uint256 minIssuanceRatioD18 = pool.issuanceRatioD18[collateralType];
Would it be bad practice to just put this on line 91 instead of creating a new variables?

2023-07-13 12:23 UTC, noahlitvin commented on protocol/synthetix/storage.dump.sol
> +        mapping(address => uint256) IssuanceRatio;
Strange that this is UpperCamelCase, maybe need to regenerate? Unsure if it matters.

2023-07-13 12:24 UTC, noahlitvin commented on protocol/synthetix/contracts/storage/Pool.sol
> +        mapping(address => bool) disabledCollaterals;
maybe this is `collateralTypeDisabled` ?

2023-07-13 12:25 UTC, noahlitvin commented on protocol/synthetix/contracts/storage/Pool.sol
> +        if (self.disabledCollaterals[collateral]) {
I think we should add the check that it's not the stablecoin here in anticipation of the cross-chain pool SIP. I can update the 326 SIP accordingly.

2023-07-27 15:57 UTC, dbeal-eth requested changes
can we implement these new pool settings using a pattern similar to what I did in my conflicting PR https://github.com/Synthetixio/synthetix-v3/pull/1730/files#diff-8c613240ec445a67e372a22ee684cac640c6d15b9468bace9db73646fec17198R200

aka having a pool collateral configuration storage type, setting the whole structure at once in `setPoolCollateralConfiguration` call, etc.

2023-08-09 14:00 UTC, closed without merging