Fix governance epoch settings storage
Synthetixio/synthetix-v3 pull request #1722
Opened 2023-07-17 14:26 UTC by mjlescano

This PR removes the `nextElectionSettings` object, and makes sure that the settings are moved the following epoch on resolution.

2023-07-18 11:23 UTC, dbeal-eth reviewed
It looks like this or gives the current owner of the election module contract control over the current, active election settings. This could be considered a governance attack vector. If thos is expected/fine, then I am ready to approve. It just seems like Amy voting parameter changes should always apply to the next epoch, the one active for the election after the next/current

2023-07-18 11:27 UTC, dbeal-eth commented on protocol/governance/contracts/storage/DebtShare.sol
> +        mapping(uint => CrossChainDebtShare.Data) crossChainDebtShareData;
Is there a deeper reason the out of bounds error was happening in the first place?

2023-07-18 11:29 UTC, dbeal-eth requested changes

2023-07-18 11:29 UTC, dbeal-eth commented on protocol/governance/contracts/storage/Election.sol
> +        // Pointer to current election settings
Not really a pointer

Btw if new settings are ever added to epoch then suddenly the whole data structure is locked. Should we do an *actual* pointer (ie mapping within another global structure) instead?

2023-07-18 13:23 UTC, leomassazza commented on protocol/governance/contracts/Proxy.sol
> +    ) UUPSProxyWithOwner(firstImplementation, initialOwner) {} // solhint-disable-line no-empty-blocks
even changing a comment will result in a new proxy deployed => change of proxy address

2023-07-18 21:57 UTC, barrasso reviewed
code changes and election module tests LGTM.

just see one cheeky failure on the `test (core-utils)` job: https://github.com/Synthetixio/synthetix-v3/actions/runs/5591845729/jobs/10223488775?pr=1722

2023-07-19 11:18 UTC, dbeal-eth approved these changes
I still have a comment unresolved regarding initOrUpgrade setting function parameters

2023-07-19 15:33 UTC, merged

2023-07-29 11:31 UTC, ajsantander reviewed
LGTM