fix reward distribution module overflow
Synthetixio/synthetix-v3 pull request #1859
Opened 2023-10-06 16:38 UTC by dbeal-eth

caused by data type size 128 instead of 256 in a big number multiplication operation

2023-10-09 10:06 UTC, jmzwar requested changes
Invalid character line 153.

Also can't divide a uint256 by int32

2023-10-09 11:43 UTC, dbeal-eth commented
> Invalid character line 153.
> 
> Also can't divide a uint256 by int32

you know this is a draft right?

also it would probably be faster if you got far enough to find these errors to just push the fixes yourself? you do have permission :laughing:

2023-10-09 12:00 UTC, jmzwar commented
> > Invalid character line 153.
> > Also can't divide a uint256 by int32
> 
> you know this is a draft right?
> 
> also it would probably be faster if you got far enough to find these errors to just push the fixes yourself? you do have permission 😆

All good. I'm adding some tests as well :)

2023-10-11 09:27 UTC, jmzwar approved these changes

2023-10-11 12:36 UTC, merged