Gas based keeper rewards
Synthetixio/synthetix-v3 pull request #1890
Opened 2023-10-30 00:18 UTC by leomassazza

2023-11-06 02:59 UTC, sunnyvempati requested changes
hope the comments make sense.  hmu in the AM with any q's.  we're very close!  great work on this

2023-11-06 02:59 UTC, sunnyvempati commented on markets/perps-market/contracts/storage/KeeperCosts.sol
> +    function getRuntime(
```suggestion
    function _processWithRuntime(
```

seems like everytime `getRuntime` is called, we usually call process so can just move it all into this private method

2023-11-06 02:59 UTC, sunnyvempati commented on markets/perps-market/contracts/storage/AsyncOrder.sol
> +                currentTotalLiquidationRewards + newLiquidationReward - oldLiquidationReward,
the `costOfExecution` here is based on the old position and needs to be recalculated for new position. and added to this line

```
uint256 newTotalLiquidationRewards = currentTotalLiquidationRewards + newLiquidationReward - oldLiquidationReward + newCostOfExecution;
uint256 requiredLiquidationRewardMargin = GlobalPerpsMarketConfiguration
  .load().minimumKeeperReward(newTotalLiquidationRewards, newCostOfExecution);
```

2023-11-06 14:12 UTC, leomassazza commented on markets/perps-market/contracts/modules/LiquidationModule.sol
> +                    account.getTotalCollateralValue(),
Thanks for noticing... you discovered a hidden bug here. It shouldn't be zero.

2023-11-06 18:02 UTC, leomassazza commented on markets/perps-market/contracts/modules/LiquidationModule.sol
> +                    flagCost,
depending on the config flagCost can be zero even if there was a flag here. (almost on some tests I got this config)

2023-11-09 19:04 UTC, sunnyvempati approved these changes
couple changes; pre-approving.  awesome work on this

2023-11-13 14:34 UTC, closed without merging

2023-11-13 14:34 UTC, noahlitvin commented
Closing in favor of #1904