Feature/extra events
Synthetixio/synthetix-v3 pull request #1905
Opened 2023-11-13 16:35 UTC by jmzwar

2023-11-13 22:18 UTC, noisekit commented on markets/perps-market/subgraph/codegen.sh
> +codegen base-goerli 84531 "synthetix-perps-market:$releaseVersion" main
this is not a correct change.

2023-11-13 22:19 UTC, noisekit commented on markets/perps-market/subgraph/subgraph.base-goerli.yaml
> +        - event: OrderCancelled(indexed uint128, indexed uint128, uint256, uint256, int128, uint256, indexed bytes32, address)
subgraphs cannot be updated in the same PR because they rely on deployed and published changes after code changes are already merged and released.

2023-11-13 22:20 UTC, noisekit requested changes
remove subgraph changes

2023-11-14 11:08 UTC, jmzwar commented on markets/perps-market/subgraph/codegen.sh
> +codegen base-goerli 84531 "synthetix-perps-market:$releaseVersion" main
this is removed from this branch

2024-09-03 04:17 UTC, closed without merging