Remove spot market
Synthetixio/synthetix-v3 pull request #2146
Opened 2024-05-10 04:25 UTC by 0xjocke

2024-05-14 05:22 UTC, davidvuong commented on markets/bfp-market/contracts/interfaces/IMarginModule.sol
>      /// @param amountDelta Amount of synths to deposit or withdraw
```suggestion
    /// @param amountDelta Amount of collateral to deposit or withdraw
```

2024-05-15 02:00 UTC, davidvuong requested changes
Left some comments

2024-05-15 04:53 UTC, 0xjocke commented on markets/bfp-market/contracts/modules/LiquidationModule.sol
> +            SYNTHETIX_CORE,
Yea I was thinking of using some kinda struct. I like this!

2024-05-21 01:23 UTC, davidvuong approved these changes
sned it

2024-05-21 01:38 UTC, merged