Allow Pool-level Rewards distributors in Perps
Synthetixio/synthetix-v3 pull request #2234
Opened 2024-08-22 15:08 UTC by noisekit

2024-08-22 15:16 UTC, dbeal-eth approved these changes
all we need to do is add a test "can add RD at zero address" or whatever

2024-08-23 10:20 UTC, noisekit commented on markets/perps-market/contracts/storage/LiquidationAssetManager.sol
> -                revert AddressError.ZeroAddress();
later in the code there is an iteration over all the collaterals configured and then their prices are used. So we end up having error that Zero-address oracle node is used.

2024-08-23 10:20 UTC, noisekit commented on markets/perps-market/contracts/storage/LiquidationAssetManager.sol
> -                revert AddressError.ZeroAddress();
so to use pool level distributors with perps we would need quite a bit more refactoring

2024-08-23 10:23 UTC, kaleb-keny requested changes
Blocked until issues resolved

2024-09-18 12:06 UTC, closed without merging